package com.ftlh.wechat.device.dao;

import com.ftlh.wechat.device.model.DeviceInfo;

public interface DeviceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    int insert(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    int insertSelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    DeviceInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    int updateByPrimaryKeySelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    int updateByPrimaryKey(DeviceInfo record);
}