package com.ftlh.wechat.device.dao;

import com.ftlh.wechat.device.model.UserDevice;

public interface UserDeviceMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_device
	 *
	 * @mbggenerated Tue Jul 25 22:57:22 CST 2017
	 */
	int deleteByPrimaryKey(String openid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_device
	 *
	 * @mbggenerated Tue Jul 25 22:57:22 CST 2017
	 */
	int insert(UserDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_device
	 *
	 * @mbggenerated Tue Jul 25 22:57:22 CST 2017
	 */
	int insertSelective(UserDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_device
	 *
	 * @mbggenerated Tue Jul 25 22:57:22 CST 2017
	 */
	UserDevice selectByPrimaryKey(String openid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_device
	 *
	 * @mbggenerated Tue Jul 25 22:57:22 CST 2017
	 */
	int updateByPrimaryKeySelective(UserDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_device
	 *
	 * @mbggenerated Tue Jul 25 22:57:22 CST 2017
	 */
	int updateByPrimaryKey(UserDevice record);
}