package com.ftlh.wechat.device.model;

public class DeviceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.id
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.deviceid
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.device_mac
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    private String deviceMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.status
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.id
     *
     * @return the value of device_info.id
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.id
     *
     * @param id the value for device_info.id
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.deviceid
     *
     * @return the value of device_info.deviceid
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.deviceid
     *
     * @param deviceid the value for device_info.deviceid
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.device_mac
     *
     * @return the value of device_info.device_mac
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    public String getDeviceMac() {
        return deviceMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.device_mac
     *
     * @param deviceMac the value for device_info.device_mac
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    public void setDeviceMac(String deviceMac) {
        this.deviceMac = deviceMac == null ? null : deviceMac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.status
     *
     * @return the value of device_info.status
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.status
     *
     * @param status the value for device_info.status
     *
     * @mbggenerated Tue Jul 25 22:53:40 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}