package com.ftlh.wechat.device.model;

import java.util.Date;

public class UserDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device.openid
     *
     * @mbggenerated Tue Jul 25 22:57:22 CST 2017
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device.device_bind
     *
     * @mbggenerated Tue Jul 25 22:57:22 CST 2017
     */
    private Integer deviceBind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device.bindtime
     *
     * @mbggenerated Tue Jul 25 22:57:22 CST 2017
     */
    private Date bindtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_device.unbindtime
     *
     * @mbggenerated Tue Jul 25 22:57:22 CST 2017
     */
    private Date unbindtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device.openid
     *
     * @return the value of user_device.openid
     *
     * @mbggenerated Tue Jul 25 22:57:22 CST 2017
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device.openid
     *
     * @param openid the value for user_device.openid
     *
     * @mbggenerated Tue Jul 25 22:57:22 CST 2017
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device.device_bind
     *
     * @return the value of user_device.device_bind
     *
     * @mbggenerated Tue Jul 25 22:57:22 CST 2017
     */
    public Integer getDeviceBind() {
        return deviceBind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device.device_bind
     *
     * @param deviceBind the value for user_device.device_bind
     *
     * @mbggenerated Tue Jul 25 22:57:22 CST 2017
     */
    public void setDeviceBind(Integer deviceBind) {
        this.deviceBind = deviceBind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device.bindtime
     *
     * @return the value of user_device.bindtime
     *
     * @mbggenerated Tue Jul 25 22:57:22 CST 2017
     */
    public Date getBindtime() {
        return bindtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device.bindtime
     *
     * @param bindtime the value for user_device.bindtime
     *
     * @mbggenerated Tue Jul 25 22:57:22 CST 2017
     */
    public void setBindtime(Date bindtime) {
        this.bindtime = bindtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_device.unbindtime
     *
     * @return the value of user_device.unbindtime
     *
     * @mbggenerated Tue Jul 25 22:57:22 CST 2017
     */
    public Date getUnbindtime() {
        return unbindtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_device.unbindtime
     *
     * @param unbindtime the value for user_device.unbindtime
     *
     * @mbggenerated Tue Jul 25 22:57:22 CST 2017
     */
    public void setUnbindtime(Date unbindtime) {
        this.unbindtime = unbindtime;
    }
}